export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS'
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR'

export const SHOW_ME_USER_BEGIN = 'SHOW_ME_USER_BEGIN';
export const SHOW_ME_USER_SUCCESS = 'SHOW_ME_USER_SUCCESS';
export const SHOW_ME_USER_ERROR = 'SHOW_ME_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';